create TABLE REGISTRATION_USER (
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)  NOT NULL ,
username varchar(100) NOT NULL,
firstname varchar(100) NOT NULL,
lastname varchar(100) DEFAULT NULL,
email varchar(100) NOT NULL,
primary key (id)
);